import { z } from "zod";
import type { EventDefinition } from "../registry";

export const aiEvents: EventDefinition[] = [
  {
    key: "ai.request.started",
    version: 1,
    publisherModuleId: "core",
    description: "An AI request was initiated.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      userId: z.string().uuid(),
      capabilityKey: z.string(),
      model: z.string(),
      provider: z.string(),
    }),
    subscribers: [],
  },
  {
    key: "ai.request.completed",
    version: 1,
    publisherModuleId: "core",
    description: "An AI request completed successfully.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      userId: z.string().uuid(),
      capabilityKey: z.string(),
      model: z.string(),
      provider: z.string(),
      inputTokens: z.number(),
      outputTokens: z.number(),
      totalTokens: z.number(),
      creditsUsed: z.number(),
      durationMs: z.number(),
    }),
    subscribers: [],
  },
  {
    key: "ai.request.failed",
    version: 1,
    publisherModuleId: "core",
    description: "An AI request failed.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      userId: z.string().uuid(),
      capabilityKey: z.string(),
      model: z.string(),
      provider: z.string(),
      error: z.string(),
      durationMs: z.number(),
    }),
    subscribers: [],
  },
  {
    key: "ai.credits.consumed",
    version: 1,
    publisherModuleId: "core",
    description: "AI credits were consumed.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      capabilityKey: z.string(),
      creditsUsed: z.number(),
      remainingCredits: z.number(),
    }),
    subscribers: [],
  },
  {
    key: "ai.credits.adjusted",
    version: 1,
    publisherModuleId: "core",
    description: "AI credits were manually adjusted by an admin.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      adminUserId: z.string().uuid(),
      adjustmentType: z.string(),
      amount: z.number(),
      reason: z.string(),
    }),
    subscribers: [],
  },
  {
    key: "ai.limit.reached",
    version: 1,
    publisherModuleId: "core",
    description: "An AI limit was reached.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      userId: z.string().uuid(),
      limitType: z.enum(["monthly", "daily", "trial"]),
      capabilityKey: z.string().optional(),
    }),
    subscribers: [],
  },
];
