import { z } from "zod";
import type { EventDefinition } from "../registry";

export const integrationEvents: EventDefinition[] = [
  {
    key: "integration.connected",
    version: 1,
    publisherModuleId: "integrations",
    description: "A new integration was connected.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      integrationId: z.string().uuid(),
      integrationName: z.string(),
      provider: z.string(),
    }),
    subscribers: [
      {
        kind: "notification",
        category: "business",
        priority: "normal",
        recipient: "company.owners",
        deepLink: "/app/integrations",
      },
    ],
  },
  {
    key: "integration.disconnected",
    version: 1,
    publisherModuleId: "integrations",
    description: "An integration was disconnected.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      integrationId: z.string().uuid(),
      integrationName: z.string(),
    }),
    subscribers: [
      {
        kind: "notification",
        category: "business",
        priority: "normal",
        recipient: "company.owners",
        deepLink: "/app/integrations",
      },
    ],
  },
  {
    key: "integration.sync.started",
    version: 1,
    publisherModuleId: "integrations",
    description: "An integration sync started.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      integrationId: z.string().uuid(),
      syncId: z.string().uuid(),
      syncType: z.string(),
    }),
    subscribers: [],
  },
  {
    key: "integration.sync.completed",
    version: 1,
    publisherModuleId: "integrations",
    description: "An integration sync completed.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      integrationId: z.string().uuid(),
      syncId: z.string().uuid(),
      recordsProcessed: z.number(),
      recordsCreated: z.number(),
      recordsUpdated: z.number(),
    }),
    subscribers: [],
  },
  {
    key: "integration.sync.failed",
    version: 1,
    publisherModuleId: "integrations",
    description: "An integration sync failed.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      integrationId: z.string().uuid(),
      syncId: z.string().uuid(),
      error: z.string(),
    }),
    subscribers: [
      {
        kind: "notification",
        category: "business",
        priority: "normal",
        recipient: "company.owners",
        deepLink: "/app/integrations",
      },
    ],
  },
  {
    key: "webhook.created",
    version: 1,
    publisherModuleId: "integrations",
    description: "A new webhook was created.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      webhookId: z.string().uuid(),
      webhookName: z.string(),
      url: z.string().url(),
    }),
    subscribers: [],
  },
  {
    key: "webhook.delivered",
    version: 1,
    publisherModuleId: "integrations",
    description: "A webhook delivery succeeded.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      webhookId: z.string().uuid(),
      eventKey: z.string(),
      status: z.string(),
      attempts: z.number(),
    }),
    subscribers: [],
  },
  {
    key: "webhook.failed",
    version: 1,
    publisherModuleId: "integrations",
    description: "A webhook delivery failed after retries.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      webhookId: z.string().uuid(),
      eventKey: z.string(),
      error: z.string(),
      attempts: z.number(),
    }),
    subscribers: [
      {
        kind: "notification",
        category: "business",
        priority: "high",
        recipient: "company.owners",
        deepLink: "/app/integrations/webhooks",
      },
    ],
  },
  {
    key: "api_key.created",
    version: 1,
    publisherModuleId: "integrations",
    description: "A new API key was created.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      apiKeyId: z.string().uuid(),
      apiKeyName: z.string(),
    }),
    subscribers: [],
  },
  {
    key: "api_key.revoked",
    version: 1,
    publisherModuleId: "integrations",
    description: "An API key was revoked.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      apiKeyId: z.string().uuid(),
      apiKeyName: z.string(),
    }),
    subscribers: [
      {
        kind: "notification",
        category: "business",
        priority: "normal",
        recipient: "company.owners",
        deepLink: "/app/integrations/api-keys",
      },
    ],
  },
  {
    key: "oauth.connected",
    version: 1,
    publisherModuleId: "integrations",
    description: "An OAuth connection was established.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      connectionId: z.string().uuid(),
      provider: z.string(),
    }),
    subscribers: [],
  },
  {
    key: "oauth.disconnected",
    version: 1,
    publisherModuleId: "integrations",
    description: "An OAuth connection was disconnected.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      connectionId: z.string().uuid(),
      provider: z.string(),
    }),
    subscribers: [],
  },
  {
    key: "import.started",
    version: 1,
    publisherModuleId: "integrations",
    description: "A data import job started.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      importId: z.string().uuid(),
      entityType: z.string(),
      format: z.string(),
    }),
    subscribers: [],
  },
  {
    key: "import.completed",
    version: 1,
    publisherModuleId: "integrations",
    description: "A data import job completed.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      importId: z.string().uuid(),
      entityType: z.string(),
      successCount: z.number(),
      errorCount: z.number(),
    }),
    subscribers: [
      {
        kind: "notification",
        category: "business",
        priority: "normal",
        recipient: "company.owners",
        deepLink: "/app/integrations/import-export",
      },
    ],
  },
  {
    key: "import.failed",
    version: 1,
    publisherModuleId: "integrations",
    description: "A data import job failed.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      importId: z.string().uuid(),
      entityType: z.string(),
      error: z.string(),
    }),
    subscribers: [
      {
        kind: "notification",
        category: "business",
        priority: "high",
        recipient: "company.owners",
        deepLink: "/app/integrations/import-export",
      },
    ],
  },
  {
    key: "export.completed",
    version: 1,
    publisherModuleId: "integrations",
    description: "A data export job completed.",
    payloadSchema: z.object({
      companyId: z.string().uuid(),
      exportId: z.string().uuid(),
      entityType: z.string(),
      format: z.string(),
      fileUrl: z.string().url(),
    }),
    subscribers: [
      {
        kind: "notification",
        category: "business",
        priority: "normal",
        recipient: "company.owners",
        deepLink: "/app/integrations/import-export",
      },
    ],
  },
];
