import type { IndustryProfile } from "./types";

export const industryProfiles: IndustryProfile[] = [
  {
    id: "retail",
    key: "retail",
    name: "Retail / Supermarket",
    description: "Point of sale, inventory, purchasing, and customer loyalty for retail stores.",
    icon: "store",
    recommendedModules: ["sales", "inventory", "commerce", "crm", "expenses", "reports"],
    recommendedWidgets: ["sales.todays_sales", "inventory.low_stock", "commerce.open_orders", "revenue.mtd"],
    defaultNavigation: [],
    terminology: { sale: "Sale", customer: "Customer", product: "Product", inventory: "Stock", order: "Order" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["sales", "inventory", "finance"],
    relevantKpis: ["daily_sales", "inventory_turnover", "avg_basket_size", "stockout_rate"],
    relevantEvents: ["sale.completed", "inventory.stock.low_detected", "payment.received"],
    relevantAiCapabilities: ["commerce.commerce_sales_prediction", "commerce.product_recommendations"],
    featureDefaults: { "commerce.native_pos": "public", "commerce.delivery": "disabled", "commerce.online_store": "beta" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "restaurant",
    key: "restaurant",
    name: "Restaurant",
    description: "Table service, kitchen orders, menu management, and reservations.",
    icon: "utensils",
    recommendedModules: ["sales", "inventory", "commerce", "crm", "expenses", "reports"],
    recommendedWidgets: ["sales.todays_sales", "commerce.open_orders", "inventory.low_stock", "revenue.mtd"],
    defaultNavigation: [],
    terminology: { sale: "Order", customer: "Guest", product: "Menu Item", inventory: "Ingredients", order: "Order" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["sales", "inventory", "commerce"],
    relevantKpis: ["table_turnover", "avg_order_value", "reservation_fulfillment", "food_cost_pct"],
    relevantEvents: ["order.created", "sale.completed", "reservation.created"],
    relevantAiCapabilities: ["commerce.order_demand_prediction", "commerce.delivery_time_prediction"],
    featureDefaults: { "commerce.native_pos": "public", "commerce.delivery": "beta", "commerce.reservations": "public" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "pharmacy",
    key: "pharmacy",
    name: "Pharmacy",
    description: "Product inventory, expiry tracking, purchasing, and customer records.",
    icon: "pill",
    recommendedModules: ["sales", "inventory", "crm", "expenses", "reports"],
    recommendedWidgets: ["sales.todays_sales", "inventory.low_stock", "inventory.expiring_soon", "revenue.mtd"],
    defaultNavigation: [],
    terminology: { sale: "Dispense", customer: "Patient", product: "Product", inventory: "Stock", order: "Order" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["sales", "inventory", "finance"],
    relevantKpis: ["prescription_volume", "expiry_risk", "stockout_rate", "avg_prescription_value"],
    relevantEvents: ["sale.completed", "inventory.stock.low_detected"],
    relevantAiCapabilities: ["inventory.inventory_turnover_analysis"],
    featureDefaults: { "inventory.expiry_tracking": "public" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "wholesale",
    key: "wholesale",
    name: "Wholesale / Distribution",
    description: "High-volume orders, warehouse management, delivery, and supplier networks.",
    icon: "truck",
    recommendedModules: ["sales", "inventory", "enterprise", "crm", "expenses", "reports"],
    recommendedWidgets: ["sales.todays_sales", "warehouse.transfers", "inventory.low_stock", "revenue.mtd"],
    defaultNavigation: [],
    terminology: { sale: "Dispatch", customer: "Customer", product: "Product", inventory: "Stock", order: "Order" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["sales", "inventory", "finance", "procurement"],
    relevantKpis: ["order_volume", "delivery_rate", "inventory_turnover", "credit_outstanding"],
    relevantEvents: ["sale.completed", "warehouse.transfer.created", "order.created"],
    relevantAiCapabilities: ["inventory.inventory_turnover_analysis"],
    featureDefaults: { "commerce.delivery": "public", "warehouse.enabled": "public" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "construction",
    key: "construction",
    name: "Construction",
    description: "Project tracking, procurement, asset management, and expense control.",
    icon: "hard-hat",
    recommendedModules: ["enterprise", "inventory", "expenses", "workflow", "reports"],
    recommendedWidgets: ["project.active_count", "expense.mtd", "asset.utilization", "procurement.pending"],
    defaultNavigation: [],
    terminology: { sale: "Invoice", customer: "Client", product: "Material", inventory: "Stock", order: "Order" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["expenses", "projects", "procurement", "assets"],
    relevantKpis: ["project_completion", "budget_variance", "asset_utilization", "procurement_cycle_time"],
    relevantEvents: ["purchase.order.created", "asset.created", "maintenance.request.created"],
    relevantAiCapabilities: ["expense.expense_anomaly_detection"],
    featureDefaults: { "projects.enabled": "public", "fleet.enabled": "beta" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "manufacturing",
    key: "manufacturing",
    name: "Manufacturing",
    description: "Production planning, inventory, maintenance, and quality control.",
    icon: "factory",
    recommendedModules: ["inventory", "enterprise", "sales", "expenses", "reports"],
    recommendedWidgets: ["production.output", "inventory.low_stock", "maintenance.open_count", "revenue.mtd"],
    defaultNavigation: [],
    terminology: { sale: "Dispatch", customer: "Customer", product: "Product", inventory: "Stock", order: "Order" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["production", "inventory", "finance", "maintenance"],
    relevantKpis: ["production_efficiency", "downtime", "quality_pass_rate", "inventory_turnover"],
    relevantEvents: ["sale.completed", "inventory.stock.low_detected", "asset.maintenance_due"],
    relevantAiCapabilities: ["inventory.inventory_turnage_analysis"],
    featureDefaults: { "production.enabled": "public", "maintenance.enabled": "public" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "service",
    key: "service",
    name: "Service Business",
    description: "Appointments, tasks, customers, invoicing, and team management.",
    icon: "briefcase",
    recommendedModules: ["sales", "crm", "workflow", "people", "expenses", "reports"],
    recommendedWidgets: ["sales.todays_sales", "workflow.open_tasks", "revenue.mtd", "customer.new_count"],
    defaultNavigation: [],
    terminology: { sale: "Invoice", customer: "Client", product: "Service", inventory: "Stock", order: "Booking" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["sales", "workflow", "finance", "people"],
    relevantKpis: ["booking_rate", "utilization", "avg_invoice_value", "client_retention"],
    relevantEvents: ["order.created", "task.created", "sale.completed"],
    relevantAiCapabilities: ["workflow.workflow_optimization"],
    featureDefaults: { "workflow.enabled": "public", "commerce.delivery": "disabled" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "hospitality",
    key: "hospitality",
    name: "Hotel / Hospitality",
    description: "Reservations, guest management, housekeeping, and revenue tracking.",
    icon: "hotel",
    recommendedModules: ["commerce", "crm", "inventory", "expenses", "reports"],
    recommendedWidgets: ["commerce.reservations_today", "revenue.mtd", "occupancy_rate", "inventory.low_stock"],
    defaultNavigation: [],
    terminology: { sale: "Charge", customer: "Guest", product: "Service", inventory: "Stock", order: "Reservation" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["commerce", "finance", "inventory"],
    relevantKpis: ["occupancy_rate", "adr", "revpar", "guest_satisfaction"],
    relevantEvents: ["commerce.reservation.created", "sale.completed"],
    relevantAiCapabilities: ["commerce.demand_prediction"],
    featureDefaults: { "commerce.reservations": "public", "commerce.delivery": "disabled" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "education",
    key: "education",
    name: "School / Education",
    description: "Student records, fees, classes, communication, and academic reporting.",
    icon: "graduation-cap",
    recommendedModules: ["people", "crm", "expenses", "reports"],
    recommendedWidgets: ["people.active_count", "revenue.mtd", "tasks.open_count", "communication.unread"],
    defaultNavigation: [],
    terminology: { sale: "Payment", customer: "Student", product: "Course", inventory: "Stock", order: "Enrollment" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["people", "finance", "communication"],
    relevantKpis: ["enrollment_rate", "fee_collection_rate", "attendance_rate", "performance_score"],
    relevantEvents: ["customer.created", "payment.received"],
    relevantAiCapabilities: [],
    featureDefaults: {},
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agriculture",
    key: "agriculture",
    name: "Agriculture",
    description: "Farm inventory, purchasing, assets, sales, and seasonal reporting.",
    icon: "sprout",
    recommendedModules: ["inventory", "sales", "enterprise", "expenses", "reports"],
    recommendedWidgets: ["inventory.low_stock", "sales.todays_sales", "asset.utilization", "revenue.mtd"],
    defaultNavigation: [],
    terminology: { sale: "Sale", customer: "Buyer", product: "Produce", inventory: "Stock", order: "Order" },
    defaultWorkflows: [],
    defaultPermissions: [],
    relevantReports: ["sales", "inventory", "finance", "assets"],
    relevantKpis: ["yield_per_hectare", "input_cost", "sales_growth", "asset_utilization"],
    relevantEvents: ["sale.completed", "purchase.order.created", "inventory.stock.low_detected"],
    relevantAiCapabilities: ["inventory.inventory_turnover_analysis"],
    featureDefaults: { "warehouse.enabled": "public", "fleet.enabled": "beta" },
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export function getIndustryProfile(key: string): IndustryProfile | undefined {
  return industryProfiles.find((p) => p.key === key);
}

export function getAllIndustryProfiles(): IndustryProfile[] {
  return industryProfiles.slice();
}
