/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PlatformRouteRouteImport } from './routes/_platform/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as PlatformDevelopersRouteImport } from './routes/_platform/developers'
import { Route as PlatformAdminRouteImport } from './routes/_platform/admin'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as PlatformDevelopersIndexRouteImport } from './routes/_platform/developers.index'
import { Route as PlatformAdminIndexRouteImport } from './routes/_platform/admin.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as PlatformDevelopersKeysRouteImport } from './routes/_platform/developers.keys'
import { Route as PlatformDevelopersDocsRouteImport } from './routes/_platform/developers.docs'
import { Route as PlatformDevelopersAppsRouteImport } from './routes/_platform/developers.apps'
import { Route as PlatformAdminUsersRouteImport } from './routes/_platform/admin.users'
import { Route as PlatformAdminSubscriptionsRouteImport } from './routes/_platform/admin.subscriptions'
import { Route as PlatformAdminModulesRouteImport } from './routes/_platform/admin.modules'
import { Route as PlatformAdminJobsRouteImport } from './routes/_platform/admin.jobs'
import { Route as PlatformAdminIntegrationsRouteImport } from './routes/_platform/admin.integrations'
import { Route as PlatformAdminIntegrationLogsRouteImport } from './routes/_platform/admin.integration-logs'
import { Route as PlatformAdminIndustryProfilesRouteImport } from './routes/_platform/admin.industry-profiles'
import { Route as PlatformAdminHealthRouteImport } from './routes/_platform/admin.health'
import { Route as PlatformAdminFeatureFlagsRouteImport } from './routes/_platform/admin.feature-flags'
import { Route as PlatformAdminEventsRouteImport } from './routes/_platform/admin.events'
import { Route as PlatformAdminCompaniesRouteImport } from './routes/_platform/admin.companies'
import { Route as PlatformAdminCommunicationsRouteImport } from './routes/_platform/admin.communications'
import { Route as PlatformAdminAuditRouteImport } from './routes/_platform/admin.audit'
import { Route as PlatformAdminApiRouteImport } from './routes/_platform/admin.api'
import { Route as PlatformAdminAnalyticsRouteImport } from './routes/_platform/admin.analytics'
import { Route as AuthenticatedAppWarehousesRouteImport } from './routes/_authenticated/app.warehouses'
import { Route as AuthenticatedAppVendorsRouteImport } from './routes/_authenticated/app.vendors'
import { Route as AuthenticatedAppSuppliersRouteImport } from './routes/_authenticated/app.suppliers'
import { Route as AuthenticatedAppStoreRouteImport } from './routes/_authenticated/app.store'
import { Route as AuthenticatedAppStockHistoryRouteImport } from './routes/_authenticated/app.stock-history'
import { Route as AuthenticatedAppSalesRouteImport } from './routes/_authenticated/app.sales'
import { Route as AuthenticatedAppReturnsRouteImport } from './routes/_authenticated/app.returns'
import { Route as AuthenticatedAppReservationsRouteImport } from './routes/_authenticated/app.reservations'
import { Route as AuthenticatedAppReceiptsRouteImport } from './routes/_authenticated/app.receipts'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app.products'
import { Route as AuthenticatedAppProcurementRouteImport } from './routes/_authenticated/app.procurement'
import { Route as AuthenticatedAppPosRouteImport } from './routes/_authenticated/app.pos'
import { Route as AuthenticatedAppPaymentsRouteImport } from './routes/_authenticated/app.payments'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppOperationsRouteImport } from './routes/_authenticated/app.operations'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppMaintenanceRouteImport } from './routes/_authenticated/app.maintenance'
import { Route as AuthenticatedAppInventoryRouteImport } from './routes/_authenticated/app.inventory'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app.integrations'
import { Route as AuthenticatedAppFleetRouteImport } from './routes/_authenticated/app.fleet'
import { Route as AuthenticatedAppFinanceRouteImport } from './routes/_authenticated/app.finance'
import { Route as AuthenticatedAppExpensesRouteImport } from './routes/_authenticated/app.expenses'
import { Route as AuthenticatedAppDeliveriesRouteImport } from './routes/_authenticated/app.deliveries'
import { Route as AuthenticatedAppCommerceRouteImport } from './routes/_authenticated/app.commerce'
import { Route as AuthenticatedAppBranchesRouteImport } from './routes/_authenticated/app.branches'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/app.assets'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/app.settings.index'
import { Route as AuthenticatedAppSalesIndexRouteImport } from './routes/_authenticated/app.sales.index'
import { Route as AuthenticatedAppOperationsIndexRouteImport } from './routes/_authenticated/app.operations.index'
import { Route as AuthenticatedAppInventoryIndexRouteImport } from './routes/_authenticated/app.inventory.index'
import { Route as AuthenticatedAppIntegrationsIndexRouteImport } from './routes/_authenticated/app.integrations.index'
import { Route as AuthenticatedAppExpensesIndexRouteImport } from './routes/_authenticated/app.expenses.index'
import { Route as ApiPublicHooksSalesIngestRouteImport } from './routes/api/public/hooks/sales-ingest'
import { Route as ApiPublicHooksJobRunnerRouteImport } from './routes/api/public/hooks/job-runner'
import { Route as ApiPublicHooksEventDispatcherRouteImport } from './routes/api/public/hooks/event-dispatcher'
import { Route as AuthenticatedAppSettingsUsersRouteImport } from './routes/_authenticated/app.settings.users'
import { Route as AuthenticatedAppSettingsSubscriptionRouteImport } from './routes/_authenticated/app.settings.subscription'
import { Route as AuthenticatedAppSettingsRolesRouteImport } from './routes/_authenticated/app.settings.roles'
import { Route as AuthenticatedAppSettingsNotificationsRouteImport } from './routes/_authenticated/app.settings.notifications'
import { Route as AuthenticatedAppSettingsModulesRouteImport } from './routes/_authenticated/app.settings.modules'
import { Route as AuthenticatedAppSettingsBranchesRouteImport } from './routes/_authenticated/app.settings.branches'
import { Route as AuthenticatedAppSettingsAuditRouteImport } from './routes/_authenticated/app.settings.audit'
import { Route as AuthenticatedAppIntegrationsWebhooksRouteImport } from './routes/_authenticated/app.integrations.webhooks'
import { Route as AuthenticatedAppIntegrationsImportExportRouteImport } from './routes/_authenticated/app.integrations.import-export'
import { Route as AuthenticatedAppIntegrationsApiKeysRouteImport } from './routes/_authenticated/app.integrations.api-keys'
import { Route as AuthenticatedAppExpensesCategoriesRouteImport } from './routes/_authenticated/app.expenses.categories'
import { Route as AuthenticatedAppAcceptInviteTokenRouteImport } from './routes/_authenticated/app.accept-invite.$token'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformDevelopersRoute = PlatformDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlatformDevelopersIndexRoute = PlatformDevelopersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformDevelopersRoute,
} as any)
const PlatformAdminIndexRoute = PlatformAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const PlatformDevelopersKeysRoute = PlatformDevelopersKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => PlatformDevelopersRoute,
} as any)
const PlatformDevelopersDocsRoute = PlatformDevelopersDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PlatformDevelopersRoute,
} as any)
const PlatformDevelopersAppsRoute = PlatformDevelopersAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => PlatformDevelopersRoute,
} as any)
const PlatformAdminUsersRoute = PlatformAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminSubscriptionsRoute =
  PlatformAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminModulesRoute = PlatformAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminJobsRoute = PlatformAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminIntegrationsRoute =
  PlatformAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminIntegrationLogsRoute =
  PlatformAdminIntegrationLogsRouteImport.update({
    id: '/integration-logs',
    path: '/integration-logs',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminIndustryProfilesRoute =
  PlatformAdminIndustryProfilesRouteImport.update({
    id: '/industry-profiles',
    path: '/industry-profiles',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminHealthRoute = PlatformAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminFeatureFlagsRoute =
  PlatformAdminFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminEventsRoute = PlatformAdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminCompaniesRoute = PlatformAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminCommunicationsRoute =
  PlatformAdminCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => PlatformAdminRoute,
  } as any)
const PlatformAdminAuditRoute = PlatformAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminApiRoute = PlatformAdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const PlatformAdminAnalyticsRoute = PlatformAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PlatformAdminRoute,
} as any)
const AuthenticatedAppWarehousesRoute =
  AuthenticatedAppWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVendorsRoute = AuthenticatedAppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSuppliersRoute =
  AuthenticatedAppSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStoreRoute = AuthenticatedAppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppStockHistoryRoute =
  AuthenticatedAppStockHistoryRouteImport.update({
    id: '/stock-history',
    path: '/stock-history',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSalesRoute = AuthenticatedAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReturnsRoute = AuthenticatedAppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReservationsRoute =
  AuthenticatedAppReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReceiptsRoute =
  AuthenticatedAppReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProcurementRoute =
  AuthenticatedAppProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPosRoute = AuthenticatedAppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPaymentsRoute =
  AuthenticatedAppPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOperationsRoute =
  AuthenticatedAppOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMaintenanceRoute =
  AuthenticatedAppMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryRoute =
  AuthenticatedAppInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFleetRoute = AuthenticatedAppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFinanceRoute = AuthenticatedAppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExpensesRoute =
  AuthenticatedAppExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDeliveriesRoute =
  AuthenticatedAppDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommerceRoute =
  AuthenticatedAppCommerceRouteImport.update({
    id: '/commerce',
    path: '/commerce',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBranchesRoute =
  AuthenticatedAppBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSalesIndexRoute =
  AuthenticatedAppSalesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppOperationsIndexRoute =
  AuthenticatedAppOperationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppOperationsRoute,
  } as any)
const AuthenticatedAppInventoryIndexRoute =
  AuthenticatedAppInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInventoryRoute,
  } as any)
const AuthenticatedAppIntegrationsIndexRoute =
  AuthenticatedAppIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppIntegrationsRoute,
  } as any)
const AuthenticatedAppExpensesIndexRoute =
  AuthenticatedAppExpensesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppExpensesRoute,
  } as any)
const ApiPublicHooksSalesIngestRoute =
  ApiPublicHooksSalesIngestRouteImport.update({
    id: '/api/public/hooks/sales-ingest',
    path: '/api/public/hooks/sales-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksJobRunnerRoute = ApiPublicHooksJobRunnerRouteImport.update({
  id: '/api/public/hooks/job-runner',
  path: '/api/public/hooks/job-runner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEventDispatcherRoute =
  ApiPublicHooksEventDispatcherRouteImport.update({
    id: '/api/public/hooks/event-dispatcher',
    path: '/api/public/hooks/event-dispatcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSettingsUsersRoute =
  AuthenticatedAppSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsSubscriptionRoute =
  AuthenticatedAppSettingsSubscriptionRouteImport.update({
    id: '/settings/subscription',
    path: '/settings/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRolesRoute =
  AuthenticatedAppSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsNotificationsRoute =
  AuthenticatedAppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsModulesRoute =
  AuthenticatedAppSettingsModulesRouteImport.update({
    id: '/settings/modules',
    path: '/settings/modules',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsBranchesRoute =
  AuthenticatedAppSettingsBranchesRouteImport.update({
    id: '/settings/branches',
    path: '/settings/branches',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsAuditRoute =
  AuthenticatedAppSettingsAuditRouteImport.update({
    id: '/settings/audit',
    path: '/settings/audit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIntegrationsWebhooksRoute =
  AuthenticatedAppIntegrationsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAppIntegrationsRoute,
  } as any)
const AuthenticatedAppIntegrationsImportExportRoute =
  AuthenticatedAppIntegrationsImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthenticatedAppIntegrationsRoute,
  } as any)
const AuthenticatedAppIntegrationsApiKeysRoute =
  AuthenticatedAppIntegrationsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAppIntegrationsRoute,
  } as any)
const AuthenticatedAppExpensesCategoriesRoute =
  AuthenticatedAppExpensesCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAppExpensesRoute,
  } as any)
const AuthenticatedAppAcceptInviteTokenRoute =
  AuthenticatedAppAcceptInviteTokenRouteImport.update({
    id: '/accept-invite/$token',
    path: '/accept-invite/$token',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin': typeof PlatformAdminRouteWithChildren
  '/developers': typeof PlatformDevelopersRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/branches': typeof AuthenticatedAppBranchesRoute
  '/app/commerce': typeof AuthenticatedAppCommerceRoute
  '/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRouteWithChildren
  '/app/finance': typeof AuthenticatedAppFinanceRoute
  '/app/fleet': typeof AuthenticatedAppFleetRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRouteWithChildren
  '/app/inventory': typeof AuthenticatedAppInventoryRouteWithChildren
  '/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/operations': typeof AuthenticatedAppOperationsRouteWithChildren
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/pos': typeof AuthenticatedAppPosRoute
  '/app/procurement': typeof AuthenticatedAppProcurementRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/receipts': typeof AuthenticatedAppReceiptsRoute
  '/app/reservations': typeof AuthenticatedAppReservationsRoute
  '/app/returns': typeof AuthenticatedAppReturnsRoute
  '/app/sales': typeof AuthenticatedAppSalesRouteWithChildren
  '/app/stock-history': typeof AuthenticatedAppStockHistoryRoute
  '/app/store': typeof AuthenticatedAppStoreRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/vendors': typeof AuthenticatedAppVendorsRoute
  '/app/warehouses': typeof AuthenticatedAppWarehousesRoute
  '/admin/analytics': typeof PlatformAdminAnalyticsRoute
  '/admin/api': typeof PlatformAdminApiRoute
  '/admin/audit': typeof PlatformAdminAuditRoute
  '/admin/communications': typeof PlatformAdminCommunicationsRoute
  '/admin/companies': typeof PlatformAdminCompaniesRoute
  '/admin/events': typeof PlatformAdminEventsRoute
  '/admin/feature-flags': typeof PlatformAdminFeatureFlagsRoute
  '/admin/health': typeof PlatformAdminHealthRoute
  '/admin/industry-profiles': typeof PlatformAdminIndustryProfilesRoute
  '/admin/integration-logs': typeof PlatformAdminIntegrationLogsRoute
  '/admin/integrations': typeof PlatformAdminIntegrationsRoute
  '/admin/jobs': typeof PlatformAdminJobsRoute
  '/admin/modules': typeof PlatformAdminModulesRoute
  '/admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/admin/users': typeof PlatformAdminUsersRoute
  '/developers/apps': typeof PlatformDevelopersAppsRoute
  '/developers/docs': typeof PlatformDevelopersDocsRoute
  '/developers/keys': typeof PlatformDevelopersKeysRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/': typeof PlatformAdminIndexRoute
  '/developers/': typeof PlatformDevelopersIndexRoute
  '/app/accept-invite/$token': typeof AuthenticatedAppAcceptInviteTokenRoute
  '/app/expenses/categories': typeof AuthenticatedAppExpensesCategoriesRoute
  '/app/integrations/api-keys': typeof AuthenticatedAppIntegrationsApiKeysRoute
  '/app/integrations/import-export': typeof AuthenticatedAppIntegrationsImportExportRoute
  '/app/integrations/webhooks': typeof AuthenticatedAppIntegrationsWebhooksRoute
  '/app/settings/audit': typeof AuthenticatedAppSettingsAuditRoute
  '/app/settings/branches': typeof AuthenticatedAppSettingsBranchesRoute
  '/app/settings/modules': typeof AuthenticatedAppSettingsModulesRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/roles': typeof AuthenticatedAppSettingsRolesRoute
  '/app/settings/subscription': typeof AuthenticatedAppSettingsSubscriptionRoute
  '/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
  '/api/public/hooks/event-dispatcher': typeof ApiPublicHooksEventDispatcherRoute
  '/api/public/hooks/job-runner': typeof ApiPublicHooksJobRunnerRoute
  '/api/public/hooks/sales-ingest': typeof ApiPublicHooksSalesIngestRoute
  '/app/expenses/': typeof AuthenticatedAppExpensesIndexRoute
  '/app/integrations/': typeof AuthenticatedAppIntegrationsIndexRoute
  '/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/app/operations/': typeof AuthenticatedAppOperationsIndexRoute
  '/app/sales/': typeof AuthenticatedAppSalesIndexRoute
  '/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/branches': typeof AuthenticatedAppBranchesRoute
  '/app/commerce': typeof AuthenticatedAppCommerceRoute
  '/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/app/finance': typeof AuthenticatedAppFinanceRoute
  '/app/fleet': typeof AuthenticatedAppFleetRoute
  '/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/pos': typeof AuthenticatedAppPosRoute
  '/app/procurement': typeof AuthenticatedAppProcurementRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/receipts': typeof AuthenticatedAppReceiptsRoute
  '/app/reservations': typeof AuthenticatedAppReservationsRoute
  '/app/returns': typeof AuthenticatedAppReturnsRoute
  '/app/stock-history': typeof AuthenticatedAppStockHistoryRoute
  '/app/store': typeof AuthenticatedAppStoreRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/app/vendors': typeof AuthenticatedAppVendorsRoute
  '/app/warehouses': typeof AuthenticatedAppWarehousesRoute
  '/admin/analytics': typeof PlatformAdminAnalyticsRoute
  '/admin/api': typeof PlatformAdminApiRoute
  '/admin/audit': typeof PlatformAdminAuditRoute
  '/admin/communications': typeof PlatformAdminCommunicationsRoute
  '/admin/companies': typeof PlatformAdminCompaniesRoute
  '/admin/events': typeof PlatformAdminEventsRoute
  '/admin/feature-flags': typeof PlatformAdminFeatureFlagsRoute
  '/admin/health': typeof PlatformAdminHealthRoute
  '/admin/industry-profiles': typeof PlatformAdminIndustryProfilesRoute
  '/admin/integration-logs': typeof PlatformAdminIntegrationLogsRoute
  '/admin/integrations': typeof PlatformAdminIntegrationsRoute
  '/admin/jobs': typeof PlatformAdminJobsRoute
  '/admin/modules': typeof PlatformAdminModulesRoute
  '/admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/admin/users': typeof PlatformAdminUsersRoute
  '/developers/apps': typeof PlatformDevelopersAppsRoute
  '/developers/docs': typeof PlatformDevelopersDocsRoute
  '/developers/keys': typeof PlatformDevelopersKeysRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin': typeof PlatformAdminIndexRoute
  '/developers': typeof PlatformDevelopersIndexRoute
  '/app/accept-invite/$token': typeof AuthenticatedAppAcceptInviteTokenRoute
  '/app/expenses/categories': typeof AuthenticatedAppExpensesCategoriesRoute
  '/app/integrations/api-keys': typeof AuthenticatedAppIntegrationsApiKeysRoute
  '/app/integrations/import-export': typeof AuthenticatedAppIntegrationsImportExportRoute
  '/app/integrations/webhooks': typeof AuthenticatedAppIntegrationsWebhooksRoute
  '/app/settings/audit': typeof AuthenticatedAppSettingsAuditRoute
  '/app/settings/branches': typeof AuthenticatedAppSettingsBranchesRoute
  '/app/settings/modules': typeof AuthenticatedAppSettingsModulesRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/roles': typeof AuthenticatedAppSettingsRolesRoute
  '/app/settings/subscription': typeof AuthenticatedAppSettingsSubscriptionRoute
  '/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
  '/api/public/hooks/event-dispatcher': typeof ApiPublicHooksEventDispatcherRoute
  '/api/public/hooks/job-runner': typeof ApiPublicHooksJobRunnerRoute
  '/api/public/hooks/sales-ingest': typeof ApiPublicHooksSalesIngestRoute
  '/app/expenses': typeof AuthenticatedAppExpensesIndexRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsIndexRoute
  '/app/inventory': typeof AuthenticatedAppInventoryIndexRoute
  '/app/operations': typeof AuthenticatedAppOperationsIndexRoute
  '/app/sales': typeof AuthenticatedAppSalesIndexRoute
  '/app/settings': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_platform': typeof PlatformRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_platform/admin': typeof PlatformAdminRouteWithChildren
  '/_platform/developers': typeof PlatformDevelopersRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/store/$slug': typeof StoreSlugRoute
  '/_authenticated/app/assets': typeof AuthenticatedAppAssetsRoute
  '/_authenticated/app/branches': typeof AuthenticatedAppBranchesRoute
  '/_authenticated/app/commerce': typeof AuthenticatedAppCommerceRoute
  '/_authenticated/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/_authenticated/app/expenses': typeof AuthenticatedAppExpensesRouteWithChildren
  '/_authenticated/app/finance': typeof AuthenticatedAppFinanceRoute
  '/_authenticated/app/fleet': typeof AuthenticatedAppFleetRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRouteWithChildren
  '/_authenticated/app/inventory': typeof AuthenticatedAppInventoryRouteWithChildren
  '/_authenticated/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/operations': typeof AuthenticatedAppOperationsRouteWithChildren
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/_authenticated/app/pos': typeof AuthenticatedAppPosRoute
  '/_authenticated/app/procurement': typeof AuthenticatedAppProcurementRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/receipts': typeof AuthenticatedAppReceiptsRoute
  '/_authenticated/app/reservations': typeof AuthenticatedAppReservationsRoute
  '/_authenticated/app/returns': typeof AuthenticatedAppReturnsRoute
  '/_authenticated/app/sales': typeof AuthenticatedAppSalesRouteWithChildren
  '/_authenticated/app/stock-history': typeof AuthenticatedAppStockHistoryRoute
  '/_authenticated/app/store': typeof AuthenticatedAppStoreRoute
  '/_authenticated/app/suppliers': typeof AuthenticatedAppSuppliersRoute
  '/_authenticated/app/vendors': typeof AuthenticatedAppVendorsRoute
  '/_authenticated/app/warehouses': typeof AuthenticatedAppWarehousesRoute
  '/_platform/admin/analytics': typeof PlatformAdminAnalyticsRoute
  '/_platform/admin/api': typeof PlatformAdminApiRoute
  '/_platform/admin/audit': typeof PlatformAdminAuditRoute
  '/_platform/admin/communications': typeof PlatformAdminCommunicationsRoute
  '/_platform/admin/companies': typeof PlatformAdminCompaniesRoute
  '/_platform/admin/events': typeof PlatformAdminEventsRoute
  '/_platform/admin/feature-flags': typeof PlatformAdminFeatureFlagsRoute
  '/_platform/admin/health': typeof PlatformAdminHealthRoute
  '/_platform/admin/industry-profiles': typeof PlatformAdminIndustryProfilesRoute
  '/_platform/admin/integration-logs': typeof PlatformAdminIntegrationLogsRoute
  '/_platform/admin/integrations': typeof PlatformAdminIntegrationsRoute
  '/_platform/admin/jobs': typeof PlatformAdminJobsRoute
  '/_platform/admin/modules': typeof PlatformAdminModulesRoute
  '/_platform/admin/subscriptions': typeof PlatformAdminSubscriptionsRoute
  '/_platform/admin/users': typeof PlatformAdminUsersRoute
  '/_platform/developers/apps': typeof PlatformDevelopersAppsRoute
  '/_platform/developers/docs': typeof PlatformDevelopersDocsRoute
  '/_platform/developers/keys': typeof PlatformDevelopersKeysRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_platform/admin/': typeof PlatformAdminIndexRoute
  '/_platform/developers/': typeof PlatformDevelopersIndexRoute
  '/_authenticated/app/accept-invite/$token': typeof AuthenticatedAppAcceptInviteTokenRoute
  '/_authenticated/app/expenses/categories': typeof AuthenticatedAppExpensesCategoriesRoute
  '/_authenticated/app/integrations/api-keys': typeof AuthenticatedAppIntegrationsApiKeysRoute
  '/_authenticated/app/integrations/import-export': typeof AuthenticatedAppIntegrationsImportExportRoute
  '/_authenticated/app/integrations/webhooks': typeof AuthenticatedAppIntegrationsWebhooksRoute
  '/_authenticated/app/settings/audit': typeof AuthenticatedAppSettingsAuditRoute
  '/_authenticated/app/settings/branches': typeof AuthenticatedAppSettingsBranchesRoute
  '/_authenticated/app/settings/modules': typeof AuthenticatedAppSettingsModulesRoute
  '/_authenticated/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/_authenticated/app/settings/roles': typeof AuthenticatedAppSettingsRolesRoute
  '/_authenticated/app/settings/subscription': typeof AuthenticatedAppSettingsSubscriptionRoute
  '/_authenticated/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
  '/api/public/hooks/event-dispatcher': typeof ApiPublicHooksEventDispatcherRoute
  '/api/public/hooks/job-runner': typeof ApiPublicHooksJobRunnerRoute
  '/api/public/hooks/sales-ingest': typeof ApiPublicHooksSalesIngestRoute
  '/_authenticated/app/expenses/': typeof AuthenticatedAppExpensesIndexRoute
  '/_authenticated/app/integrations/': typeof AuthenticatedAppIntegrationsIndexRoute
  '/_authenticated/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/_authenticated/app/operations/': typeof AuthenticatedAppOperationsIndexRoute
  '/_authenticated/app/sales/': typeof AuthenticatedAppSalesIndexRoute
  '/_authenticated/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/app'
    | '/onboarding'
    | '/admin'
    | '/developers'
    | '/legal/privacy'
    | '/legal/terms'
    | '/store/$slug'
    | '/app/assets'
    | '/app/branches'
    | '/app/commerce'
    | '/app/deliveries'
    | '/app/expenses'
    | '/app/finance'
    | '/app/fleet'
    | '/app/integrations'
    | '/app/inventory'
    | '/app/maintenance'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/operations'
    | '/app/orders'
    | '/app/payments'
    | '/app/pos'
    | '/app/procurement'
    | '/app/products'
    | '/app/receipts'
    | '/app/reservations'
    | '/app/returns'
    | '/app/sales'
    | '/app/stock-history'
    | '/app/store'
    | '/app/suppliers'
    | '/app/vendors'
    | '/app/warehouses'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/communications'
    | '/admin/companies'
    | '/admin/events'
    | '/admin/feature-flags'
    | '/admin/health'
    | '/admin/industry-profiles'
    | '/admin/integration-logs'
    | '/admin/integrations'
    | '/admin/jobs'
    | '/admin/modules'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/developers/apps'
    | '/developers/docs'
    | '/developers/keys'
    | '/app/'
    | '/admin/'
    | '/developers/'
    | '/app/accept-invite/$token'
    | '/app/expenses/categories'
    | '/app/integrations/api-keys'
    | '/app/integrations/import-export'
    | '/app/integrations/webhooks'
    | '/app/settings/audit'
    | '/app/settings/branches'
    | '/app/settings/modules'
    | '/app/settings/notifications'
    | '/app/settings/roles'
    | '/app/settings/subscription'
    | '/app/settings/users'
    | '/api/public/hooks/event-dispatcher'
    | '/api/public/hooks/job-runner'
    | '/api/public/hooks/sales-ingest'
    | '/app/expenses/'
    | '/app/integrations/'
    | '/app/inventory/'
    | '/app/operations/'
    | '/app/sales/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/onboarding'
    | '/legal/privacy'
    | '/legal/terms'
    | '/store/$slug'
    | '/app/assets'
    | '/app/branches'
    | '/app/commerce'
    | '/app/deliveries'
    | '/app/finance'
    | '/app/fleet'
    | '/app/maintenance'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/orders'
    | '/app/payments'
    | '/app/pos'
    | '/app/procurement'
    | '/app/products'
    | '/app/receipts'
    | '/app/reservations'
    | '/app/returns'
    | '/app/stock-history'
    | '/app/store'
    | '/app/suppliers'
    | '/app/vendors'
    | '/app/warehouses'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/communications'
    | '/admin/companies'
    | '/admin/events'
    | '/admin/feature-flags'
    | '/admin/health'
    | '/admin/industry-profiles'
    | '/admin/integration-logs'
    | '/admin/integrations'
    | '/admin/jobs'
    | '/admin/modules'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/developers/apps'
    | '/developers/docs'
    | '/developers/keys'
    | '/app'
    | '/admin'
    | '/developers'
    | '/app/accept-invite/$token'
    | '/app/expenses/categories'
    | '/app/integrations/api-keys'
    | '/app/integrations/import-export'
    | '/app/integrations/webhooks'
    | '/app/settings/audit'
    | '/app/settings/branches'
    | '/app/settings/modules'
    | '/app/settings/notifications'
    | '/app/settings/roles'
    | '/app/settings/subscription'
    | '/app/settings/users'
    | '/api/public/hooks/event-dispatcher'
    | '/api/public/hooks/job-runner'
    | '/api/public/hooks/sales-ingest'
    | '/app/expenses'
    | '/app/integrations'
    | '/app/inventory'
    | '/app/operations'
    | '/app/sales'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_platform'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_platform/admin'
    | '/_platform/developers'
    | '/legal/privacy'
    | '/legal/terms'
    | '/store/$slug'
    | '/_authenticated/app/assets'
    | '/_authenticated/app/branches'
    | '/_authenticated/app/commerce'
    | '/_authenticated/app/deliveries'
    | '/_authenticated/app/expenses'
    | '/_authenticated/app/finance'
    | '/_authenticated/app/fleet'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/inventory'
    | '/_authenticated/app/maintenance'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/operations'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/payments'
    | '/_authenticated/app/pos'
    | '/_authenticated/app/procurement'
    | '/_authenticated/app/products'
    | '/_authenticated/app/receipts'
    | '/_authenticated/app/reservations'
    | '/_authenticated/app/returns'
    | '/_authenticated/app/sales'
    | '/_authenticated/app/stock-history'
    | '/_authenticated/app/store'
    | '/_authenticated/app/suppliers'
    | '/_authenticated/app/vendors'
    | '/_authenticated/app/warehouses'
    | '/_platform/admin/analytics'
    | '/_platform/admin/api'
    | '/_platform/admin/audit'
    | '/_platform/admin/communications'
    | '/_platform/admin/companies'
    | '/_platform/admin/events'
    | '/_platform/admin/feature-flags'
    | '/_platform/admin/health'
    | '/_platform/admin/industry-profiles'
    | '/_platform/admin/integration-logs'
    | '/_platform/admin/integrations'
    | '/_platform/admin/jobs'
    | '/_platform/admin/modules'
    | '/_platform/admin/subscriptions'
    | '/_platform/admin/users'
    | '/_platform/developers/apps'
    | '/_platform/developers/docs'
    | '/_platform/developers/keys'
    | '/_authenticated/app/'
    | '/_platform/admin/'
    | '/_platform/developers/'
    | '/_authenticated/app/accept-invite/$token'
    | '/_authenticated/app/expenses/categories'
    | '/_authenticated/app/integrations/api-keys'
    | '/_authenticated/app/integrations/import-export'
    | '/_authenticated/app/integrations/webhooks'
    | '/_authenticated/app/settings/audit'
    | '/_authenticated/app/settings/branches'
    | '/_authenticated/app/settings/modules'
    | '/_authenticated/app/settings/notifications'
    | '/_authenticated/app/settings/roles'
    | '/_authenticated/app/settings/subscription'
    | '/_authenticated/app/settings/users'
    | '/api/public/hooks/event-dispatcher'
    | '/api/public/hooks/job-runner'
    | '/api/public/hooks/sales-ingest'
    | '/_authenticated/app/expenses/'
    | '/_authenticated/app/integrations/'
    | '/_authenticated/app/inventory/'
    | '/_authenticated/app/operations/'
    | '/_authenticated/app/sales/'
    | '/_authenticated/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  StoreSlugRoute: typeof StoreSlugRoute
  ApiPublicHooksEventDispatcherRoute: typeof ApiPublicHooksEventDispatcherRoute
  ApiPublicHooksJobRunnerRoute: typeof ApiPublicHooksJobRunnerRoute
  ApiPublicHooksSalesIngestRoute: typeof ApiPublicHooksSalesIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/developers': {
      id: '/_platform/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof PlatformDevelopersRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/admin': {
      id: '/_platform/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_platform/developers/': {
      id: '/_platform/developers/'
      path: '/'
      fullPath: '/developers/'
      preLoaderRoute: typeof PlatformDevelopersIndexRouteImport
      parentRoute: typeof PlatformDevelopersRoute
    }
    '/_platform/admin/': {
      id: '/_platform/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof PlatformAdminIndexRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_platform/developers/keys': {
      id: '/_platform/developers/keys'
      path: '/keys'
      fullPath: '/developers/keys'
      preLoaderRoute: typeof PlatformDevelopersKeysRouteImport
      parentRoute: typeof PlatformDevelopersRoute
    }
    '/_platform/developers/docs': {
      id: '/_platform/developers/docs'
      path: '/docs'
      fullPath: '/developers/docs'
      preLoaderRoute: typeof PlatformDevelopersDocsRouteImport
      parentRoute: typeof PlatformDevelopersRoute
    }
    '/_platform/developers/apps': {
      id: '/_platform/developers/apps'
      path: '/apps'
      fullPath: '/developers/apps'
      preLoaderRoute: typeof PlatformDevelopersAppsRouteImport
      parentRoute: typeof PlatformDevelopersRoute
    }
    '/_platform/admin/users': {
      id: '/_platform/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof PlatformAdminUsersRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/subscriptions': {
      id: '/_platform/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof PlatformAdminSubscriptionsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/modules': {
      id: '/_platform/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof PlatformAdminModulesRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/jobs': {
      id: '/_platform/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof PlatformAdminJobsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/integrations': {
      id: '/_platform/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof PlatformAdminIntegrationsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/integration-logs': {
      id: '/_platform/admin/integration-logs'
      path: '/integration-logs'
      fullPath: '/admin/integration-logs'
      preLoaderRoute: typeof PlatformAdminIntegrationLogsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/industry-profiles': {
      id: '/_platform/admin/industry-profiles'
      path: '/industry-profiles'
      fullPath: '/admin/industry-profiles'
      preLoaderRoute: typeof PlatformAdminIndustryProfilesRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/health': {
      id: '/_platform/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof PlatformAdminHealthRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/feature-flags': {
      id: '/_platform/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof PlatformAdminFeatureFlagsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/events': {
      id: '/_platform/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof PlatformAdminEventsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/companies': {
      id: '/_platform/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof PlatformAdminCompaniesRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/communications': {
      id: '/_platform/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof PlatformAdminCommunicationsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/audit': {
      id: '/_platform/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof PlatformAdminAuditRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/api': {
      id: '/_platform/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof PlatformAdminApiRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_platform/admin/analytics': {
      id: '/_platform/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof PlatformAdminAnalyticsRouteImport
      parentRoute: typeof PlatformAdminRoute
    }
    '/_authenticated/app/warehouses': {
      id: '/_authenticated/app/warehouses'
      path: '/warehouses'
      fullPath: '/app/warehouses'
      preLoaderRoute: typeof AuthenticatedAppWarehousesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vendors': {
      id: '/_authenticated/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AuthenticatedAppVendorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/suppliers': {
      id: '/_authenticated/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AuthenticatedAppSuppliersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/store': {
      id: '/_authenticated/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AuthenticatedAppStoreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/stock-history': {
      id: '/_authenticated/app/stock-history'
      path: '/stock-history'
      fullPath: '/app/stock-history'
      preLoaderRoute: typeof AuthenticatedAppStockHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sales': {
      id: '/_authenticated/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AuthenticatedAppSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/returns': {
      id: '/_authenticated/app/returns'
      path: '/returns'
      fullPath: '/app/returns'
      preLoaderRoute: typeof AuthenticatedAppReturnsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reservations': {
      id: '/_authenticated/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AuthenticatedAppReservationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/receipts': {
      id: '/_authenticated/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AuthenticatedAppReceiptsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/procurement': {
      id: '/_authenticated/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AuthenticatedAppProcurementRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pos': {
      id: '/_authenticated/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AuthenticatedAppPosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/payments': {
      id: '/_authenticated/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AuthenticatedAppPaymentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/operations': {
      id: '/_authenticated/app/operations'
      path: '/operations'
      fullPath: '/app/operations'
      preLoaderRoute: typeof AuthenticatedAppOperationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/maintenance': {
      id: '/_authenticated/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory': {
      id: '/_authenticated/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AuthenticatedAppInventoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/fleet': {
      id: '/_authenticated/app/fleet'
      path: '/fleet'
      fullPath: '/app/fleet'
      preLoaderRoute: typeof AuthenticatedAppFleetRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/finance': {
      id: '/_authenticated/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AuthenticatedAppFinanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/expenses': {
      id: '/_authenticated/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AuthenticatedAppExpensesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deliveries': {
      id: '/_authenticated/app/deliveries'
      path: '/deliveries'
      fullPath: '/app/deliveries'
      preLoaderRoute: typeof AuthenticatedAppDeliveriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/commerce': {
      id: '/_authenticated/app/commerce'
      path: '/commerce'
      fullPath: '/app/commerce'
      preLoaderRoute: typeof AuthenticatedAppCommerceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/branches': {
      id: '/_authenticated/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AuthenticatedAppBranchesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assets': {
      id: '/_authenticated/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/': {
      id: '/_authenticated/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sales/': {
      id: '/_authenticated/app/sales/'
      path: '/'
      fullPath: '/app/sales/'
      preLoaderRoute: typeof AuthenticatedAppSalesIndexRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/operations/': {
      id: '/_authenticated/app/operations/'
      path: '/'
      fullPath: '/app/operations/'
      preLoaderRoute: typeof AuthenticatedAppOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppOperationsRoute
    }
    '/_authenticated/app/inventory/': {
      id: '/_authenticated/app/inventory/'
      path: '/'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AuthenticatedAppInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedAppInventoryRoute
    }
    '/_authenticated/app/integrations/': {
      id: '/_authenticated/app/integrations/'
      path: '/'
      fullPath: '/app/integrations/'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppIntegrationsRoute
    }
    '/_authenticated/app/expenses/': {
      id: '/_authenticated/app/expenses/'
      path: '/'
      fullPath: '/app/expenses/'
      preLoaderRoute: typeof AuthenticatedAppExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedAppExpensesRoute
    }
    '/api/public/hooks/sales-ingest': {
      id: '/api/public/hooks/sales-ingest'
      path: '/api/public/hooks/sales-ingest'
      fullPath: '/api/public/hooks/sales-ingest'
      preLoaderRoute: typeof ApiPublicHooksSalesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/job-runner': {
      id: '/api/public/hooks/job-runner'
      path: '/api/public/hooks/job-runner'
      fullPath: '/api/public/hooks/job-runner'
      preLoaderRoute: typeof ApiPublicHooksJobRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/event-dispatcher': {
      id: '/api/public/hooks/event-dispatcher'
      path: '/api/public/hooks/event-dispatcher'
      fullPath: '/api/public/hooks/event-dispatcher'
      preLoaderRoute: typeof ApiPublicHooksEventDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/settings/users': {
      id: '/_authenticated/app/settings/users'
      path: '/settings/users'
      fullPath: '/app/settings/users'
      preLoaderRoute: typeof AuthenticatedAppSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/subscription': {
      id: '/_authenticated/app/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/app/settings/subscription'
      preLoaderRoute: typeof AuthenticatedAppSettingsSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/roles': {
      id: '/_authenticated/app/settings/roles'
      path: '/settings/roles'
      fullPath: '/app/settings/roles'
      preLoaderRoute: typeof AuthenticatedAppSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/notifications': {
      id: '/_authenticated/app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/modules': {
      id: '/_authenticated/app/settings/modules'
      path: '/settings/modules'
      fullPath: '/app/settings/modules'
      preLoaderRoute: typeof AuthenticatedAppSettingsModulesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/branches': {
      id: '/_authenticated/app/settings/branches'
      path: '/settings/branches'
      fullPath: '/app/settings/branches'
      preLoaderRoute: typeof AuthenticatedAppSettingsBranchesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/audit': {
      id: '/_authenticated/app/settings/audit'
      path: '/settings/audit'
      fullPath: '/app/settings/audit'
      preLoaderRoute: typeof AuthenticatedAppSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations/webhooks': {
      id: '/_authenticated/app/integrations/webhooks'
      path: '/webhooks'
      fullPath: '/app/integrations/webhooks'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsWebhooksRouteImport
      parentRoute: typeof AuthenticatedAppIntegrationsRoute
    }
    '/_authenticated/app/integrations/import-export': {
      id: '/_authenticated/app/integrations/import-export'
      path: '/import-export'
      fullPath: '/app/integrations/import-export'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsImportExportRouteImport
      parentRoute: typeof AuthenticatedAppIntegrationsRoute
    }
    '/_authenticated/app/integrations/api-keys': {
      id: '/_authenticated/app/integrations/api-keys'
      path: '/api-keys'
      fullPath: '/app/integrations/api-keys'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsApiKeysRouteImport
      parentRoute: typeof AuthenticatedAppIntegrationsRoute
    }
    '/_authenticated/app/expenses/categories': {
      id: '/_authenticated/app/expenses/categories'
      path: '/categories'
      fullPath: '/app/expenses/categories'
      preLoaderRoute: typeof AuthenticatedAppExpensesCategoriesRouteImport
      parentRoute: typeof AuthenticatedAppExpensesRoute
    }
    '/_authenticated/app/accept-invite/$token': {
      id: '/_authenticated/app/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/app/accept-invite/$token'
      preLoaderRoute: typeof AuthenticatedAppAcceptInviteTokenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppExpensesRouteChildren {
  AuthenticatedAppExpensesCategoriesRoute: typeof AuthenticatedAppExpensesCategoriesRoute
  AuthenticatedAppExpensesIndexRoute: typeof AuthenticatedAppExpensesIndexRoute
}

const AuthenticatedAppExpensesRouteChildren: AuthenticatedAppExpensesRouteChildren =
  {
    AuthenticatedAppExpensesCategoriesRoute:
      AuthenticatedAppExpensesCategoriesRoute,
    AuthenticatedAppExpensesIndexRoute: AuthenticatedAppExpensesIndexRoute,
  }

const AuthenticatedAppExpensesRouteWithChildren =
  AuthenticatedAppExpensesRoute._addFileChildren(
    AuthenticatedAppExpensesRouteChildren,
  )

interface AuthenticatedAppIntegrationsRouteChildren {
  AuthenticatedAppIntegrationsApiKeysRoute: typeof AuthenticatedAppIntegrationsApiKeysRoute
  AuthenticatedAppIntegrationsImportExportRoute: typeof AuthenticatedAppIntegrationsImportExportRoute
  AuthenticatedAppIntegrationsWebhooksRoute: typeof AuthenticatedAppIntegrationsWebhooksRoute
  AuthenticatedAppIntegrationsIndexRoute: typeof AuthenticatedAppIntegrationsIndexRoute
}

const AuthenticatedAppIntegrationsRouteChildren: AuthenticatedAppIntegrationsRouteChildren =
  {
    AuthenticatedAppIntegrationsApiKeysRoute:
      AuthenticatedAppIntegrationsApiKeysRoute,
    AuthenticatedAppIntegrationsImportExportRoute:
      AuthenticatedAppIntegrationsImportExportRoute,
    AuthenticatedAppIntegrationsWebhooksRoute:
      AuthenticatedAppIntegrationsWebhooksRoute,
    AuthenticatedAppIntegrationsIndexRoute:
      AuthenticatedAppIntegrationsIndexRoute,
  }

const AuthenticatedAppIntegrationsRouteWithChildren =
  AuthenticatedAppIntegrationsRoute._addFileChildren(
    AuthenticatedAppIntegrationsRouteChildren,
  )

interface AuthenticatedAppInventoryRouteChildren {
  AuthenticatedAppInventoryIndexRoute: typeof AuthenticatedAppInventoryIndexRoute
}

const AuthenticatedAppInventoryRouteChildren: AuthenticatedAppInventoryRouteChildren =
  {
    AuthenticatedAppInventoryIndexRoute: AuthenticatedAppInventoryIndexRoute,
  }

const AuthenticatedAppInventoryRouteWithChildren =
  AuthenticatedAppInventoryRoute._addFileChildren(
    AuthenticatedAppInventoryRouteChildren,
  )

interface AuthenticatedAppOperationsRouteChildren {
  AuthenticatedAppOperationsIndexRoute: typeof AuthenticatedAppOperationsIndexRoute
}

const AuthenticatedAppOperationsRouteChildren: AuthenticatedAppOperationsRouteChildren =
  {
    AuthenticatedAppOperationsIndexRoute: AuthenticatedAppOperationsIndexRoute,
  }

const AuthenticatedAppOperationsRouteWithChildren =
  AuthenticatedAppOperationsRoute._addFileChildren(
    AuthenticatedAppOperationsRouteChildren,
  )

interface AuthenticatedAppSalesRouteChildren {
  AuthenticatedAppSalesIndexRoute: typeof AuthenticatedAppSalesIndexRoute
}

const AuthenticatedAppSalesRouteChildren: AuthenticatedAppSalesRouteChildren = {
  AuthenticatedAppSalesIndexRoute: AuthenticatedAppSalesIndexRoute,
}

const AuthenticatedAppSalesRouteWithChildren =
  AuthenticatedAppSalesRoute._addFileChildren(
    AuthenticatedAppSalesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRoute
  AuthenticatedAppBranchesRoute: typeof AuthenticatedAppBranchesRoute
  AuthenticatedAppCommerceRoute: typeof AuthenticatedAppCommerceRoute
  AuthenticatedAppDeliveriesRoute: typeof AuthenticatedAppDeliveriesRoute
  AuthenticatedAppExpensesRoute: typeof AuthenticatedAppExpensesRouteWithChildren
  AuthenticatedAppFinanceRoute: typeof AuthenticatedAppFinanceRoute
  AuthenticatedAppFleetRoute: typeof AuthenticatedAppFleetRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRouteWithChildren
  AuthenticatedAppInventoryRoute: typeof AuthenticatedAppInventoryRouteWithChildren
  AuthenticatedAppMaintenanceRoute: typeof AuthenticatedAppMaintenanceRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppOperationsRoute: typeof AuthenticatedAppOperationsRouteWithChildren
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppPaymentsRoute: typeof AuthenticatedAppPaymentsRoute
  AuthenticatedAppPosRoute: typeof AuthenticatedAppPosRoute
  AuthenticatedAppProcurementRoute: typeof AuthenticatedAppProcurementRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppReceiptsRoute: typeof AuthenticatedAppReceiptsRoute
  AuthenticatedAppReservationsRoute: typeof AuthenticatedAppReservationsRoute
  AuthenticatedAppReturnsRoute: typeof AuthenticatedAppReturnsRoute
  AuthenticatedAppSalesRoute: typeof AuthenticatedAppSalesRouteWithChildren
  AuthenticatedAppStockHistoryRoute: typeof AuthenticatedAppStockHistoryRoute
  AuthenticatedAppStoreRoute: typeof AuthenticatedAppStoreRoute
  AuthenticatedAppSuppliersRoute: typeof AuthenticatedAppSuppliersRoute
  AuthenticatedAppVendorsRoute: typeof AuthenticatedAppVendorsRoute
  AuthenticatedAppWarehousesRoute: typeof AuthenticatedAppWarehousesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAcceptInviteTokenRoute: typeof AuthenticatedAppAcceptInviteTokenRoute
  AuthenticatedAppSettingsAuditRoute: typeof AuthenticatedAppSettingsAuditRoute
  AuthenticatedAppSettingsBranchesRoute: typeof AuthenticatedAppSettingsBranchesRoute
  AuthenticatedAppSettingsModulesRoute: typeof AuthenticatedAppSettingsModulesRoute
  AuthenticatedAppSettingsNotificationsRoute: typeof AuthenticatedAppSettingsNotificationsRoute
  AuthenticatedAppSettingsRolesRoute: typeof AuthenticatedAppSettingsRolesRoute
  AuthenticatedAppSettingsSubscriptionRoute: typeof AuthenticatedAppSettingsSubscriptionRoute
  AuthenticatedAppSettingsUsersRoute: typeof AuthenticatedAppSettingsUsersRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRoute,
  AuthenticatedAppBranchesRoute: AuthenticatedAppBranchesRoute,
  AuthenticatedAppCommerceRoute: AuthenticatedAppCommerceRoute,
  AuthenticatedAppDeliveriesRoute: AuthenticatedAppDeliveriesRoute,
  AuthenticatedAppExpensesRoute: AuthenticatedAppExpensesRouteWithChildren,
  AuthenticatedAppFinanceRoute: AuthenticatedAppFinanceRoute,
  AuthenticatedAppFleetRoute: AuthenticatedAppFleetRoute,
  AuthenticatedAppIntegrationsRoute:
    AuthenticatedAppIntegrationsRouteWithChildren,
  AuthenticatedAppInventoryRoute: AuthenticatedAppInventoryRouteWithChildren,
  AuthenticatedAppMaintenanceRoute: AuthenticatedAppMaintenanceRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppOperationsRoute: AuthenticatedAppOperationsRouteWithChildren,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppPaymentsRoute: AuthenticatedAppPaymentsRoute,
  AuthenticatedAppPosRoute: AuthenticatedAppPosRoute,
  AuthenticatedAppProcurementRoute: AuthenticatedAppProcurementRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppReceiptsRoute: AuthenticatedAppReceiptsRoute,
  AuthenticatedAppReservationsRoute: AuthenticatedAppReservationsRoute,
  AuthenticatedAppReturnsRoute: AuthenticatedAppReturnsRoute,
  AuthenticatedAppSalesRoute: AuthenticatedAppSalesRouteWithChildren,
  AuthenticatedAppStockHistoryRoute: AuthenticatedAppStockHistoryRoute,
  AuthenticatedAppStoreRoute: AuthenticatedAppStoreRoute,
  AuthenticatedAppSuppliersRoute: AuthenticatedAppSuppliersRoute,
  AuthenticatedAppVendorsRoute: AuthenticatedAppVendorsRoute,
  AuthenticatedAppWarehousesRoute: AuthenticatedAppWarehousesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAcceptInviteTokenRoute:
    AuthenticatedAppAcceptInviteTokenRoute,
  AuthenticatedAppSettingsAuditRoute: AuthenticatedAppSettingsAuditRoute,
  AuthenticatedAppSettingsBranchesRoute: AuthenticatedAppSettingsBranchesRoute,
  AuthenticatedAppSettingsModulesRoute: AuthenticatedAppSettingsModulesRoute,
  AuthenticatedAppSettingsNotificationsRoute:
    AuthenticatedAppSettingsNotificationsRoute,
  AuthenticatedAppSettingsRolesRoute: AuthenticatedAppSettingsRolesRoute,
  AuthenticatedAppSettingsSubscriptionRoute:
    AuthenticatedAppSettingsSubscriptionRoute,
  AuthenticatedAppSettingsUsersRoute: AuthenticatedAppSettingsUsersRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformAdminRouteChildren {
  PlatformAdminAnalyticsRoute: typeof PlatformAdminAnalyticsRoute
  PlatformAdminApiRoute: typeof PlatformAdminApiRoute
  PlatformAdminAuditRoute: typeof PlatformAdminAuditRoute
  PlatformAdminCommunicationsRoute: typeof PlatformAdminCommunicationsRoute
  PlatformAdminCompaniesRoute: typeof PlatformAdminCompaniesRoute
  PlatformAdminEventsRoute: typeof PlatformAdminEventsRoute
  PlatformAdminFeatureFlagsRoute: typeof PlatformAdminFeatureFlagsRoute
  PlatformAdminHealthRoute: typeof PlatformAdminHealthRoute
  PlatformAdminIndustryProfilesRoute: typeof PlatformAdminIndustryProfilesRoute
  PlatformAdminIntegrationLogsRoute: typeof PlatformAdminIntegrationLogsRoute
  PlatformAdminIntegrationsRoute: typeof PlatformAdminIntegrationsRoute
  PlatformAdminJobsRoute: typeof PlatformAdminJobsRoute
  PlatformAdminModulesRoute: typeof PlatformAdminModulesRoute
  PlatformAdminSubscriptionsRoute: typeof PlatformAdminSubscriptionsRoute
  PlatformAdminUsersRoute: typeof PlatformAdminUsersRoute
  PlatformAdminIndexRoute: typeof PlatformAdminIndexRoute
}

const PlatformAdminRouteChildren: PlatformAdminRouteChildren = {
  PlatformAdminAnalyticsRoute: PlatformAdminAnalyticsRoute,
  PlatformAdminApiRoute: PlatformAdminApiRoute,
  PlatformAdminAuditRoute: PlatformAdminAuditRoute,
  PlatformAdminCommunicationsRoute: PlatformAdminCommunicationsRoute,
  PlatformAdminCompaniesRoute: PlatformAdminCompaniesRoute,
  PlatformAdminEventsRoute: PlatformAdminEventsRoute,
  PlatformAdminFeatureFlagsRoute: PlatformAdminFeatureFlagsRoute,
  PlatformAdminHealthRoute: PlatformAdminHealthRoute,
  PlatformAdminIndustryProfilesRoute: PlatformAdminIndustryProfilesRoute,
  PlatformAdminIntegrationLogsRoute: PlatformAdminIntegrationLogsRoute,
  PlatformAdminIntegrationsRoute: PlatformAdminIntegrationsRoute,
  PlatformAdminJobsRoute: PlatformAdminJobsRoute,
  PlatformAdminModulesRoute: PlatformAdminModulesRoute,
  PlatformAdminSubscriptionsRoute: PlatformAdminSubscriptionsRoute,
  PlatformAdminUsersRoute: PlatformAdminUsersRoute,
  PlatformAdminIndexRoute: PlatformAdminIndexRoute,
}

const PlatformAdminRouteWithChildren = PlatformAdminRoute._addFileChildren(
  PlatformAdminRouteChildren,
)

interface PlatformDevelopersRouteChildren {
  PlatformDevelopersAppsRoute: typeof PlatformDevelopersAppsRoute
  PlatformDevelopersDocsRoute: typeof PlatformDevelopersDocsRoute
  PlatformDevelopersKeysRoute: typeof PlatformDevelopersKeysRoute
  PlatformDevelopersIndexRoute: typeof PlatformDevelopersIndexRoute
}

const PlatformDevelopersRouteChildren: PlatformDevelopersRouteChildren = {
  PlatformDevelopersAppsRoute: PlatformDevelopersAppsRoute,
  PlatformDevelopersDocsRoute: PlatformDevelopersDocsRoute,
  PlatformDevelopersKeysRoute: PlatformDevelopersKeysRoute,
  PlatformDevelopersIndexRoute: PlatformDevelopersIndexRoute,
}

const PlatformDevelopersRouteWithChildren =
  PlatformDevelopersRoute._addFileChildren(PlatformDevelopersRouteChildren)

interface PlatformRouteRouteChildren {
  PlatformAdminRoute: typeof PlatformAdminRouteWithChildren
  PlatformDevelopersRoute: typeof PlatformDevelopersRouteWithChildren
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformAdminRoute: PlatformAdminRouteWithChildren,
  PlatformDevelopersRoute: PlatformDevelopersRouteWithChildren,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  StoreSlugRoute: StoreSlugRoute,
  ApiPublicHooksEventDispatcherRoute: ApiPublicHooksEventDispatcherRoute,
  ApiPublicHooksJobRunnerRoute: ApiPublicHooksJobRunnerRoute,
  ApiPublicHooksSalesIngestRoute: ApiPublicHooksSalesIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
